/**
 * Component Prop Contracts
 *
 * Defines TypeScript interfaces for all component props in the expense tracking feature.
 * These contracts serve as the "API" between components and enforce type safety.
 */

import { Expense, ExpenseCategory, ExpenseSummary } from '../../../src/server/types/expense';

// ============================================================================
// ExpenseForm Component
// ============================================================================

/**
 * Props for the ExpenseForm component
 * Handles user input for creating new expenses
 */
export interface ExpenseFormProps {
  /**
   * Callback invoked when user submits a valid expense
   * @param expense - The new expense to add (without id/createdAt, generated by parent)
   */
  onAddExpense: (expense: Omit<Expense, 'id' | 'createdAt'>) => void;

  /**
   * Optional CSS class name for styling
   */
  className?: string;
}

/**
 * Internal form state (not a prop, but documents the component's internal contract)
 */
export interface ExpenseFormState {
  amount: string;          // String to allow empty state and decimal input
  date: string;            // ISO 8601 date string (YYYY-MM-DD)
  category: ExpenseCategory | '';  // Empty string for unselected state
  description: string;
}

// ============================================================================
// ExpenseList Component
// ============================================================================

/**
 * Props for the ExpenseList component
 * Displays all expenses with delete functionality
 */
export interface ExpenseListProps {
  /**
   * Array of expenses to display (should be pre-sorted by parent)
   */
  expenses: Expense[];

  /**
   * Callback invoked when user clicks delete on an expense
   * @param id - The unique ID of the expense to delete
   */
  onDeleteExpense: (id: string) => void;

  /**
   * Optional CSS class name for styling
   */
  className?: string;
}

/**
 * Props for individual ExpenseItem sub-component
 */
export interface ExpenseItemProps {
  /**
   * The expense to display
   */
  expense: Expense;

  /**
   * Callback invoked when delete button is clicked
   */
  onDelete: () => void;
}

// ============================================================================
// ExpenseSummary Component
// ============================================================================

/**
 * Props for the ExpenseSummary component
 * Displays calculated totals and breakdowns
 */
export interface ExpenseSummaryProps {
  /**
   * Pre-calculated summary statistics
   * (Calculations should be done by parent/custom hook)
   */
  summary: ExpenseSummary;

  /**
   * Optional CSS class name for styling
   */
  className?: string;
}

// ============================================================================
// Main Dashboard Page
// ============================================================================

/**
 * Props for the main dashboard page component
 * (Next.js pages don't receive props by default, but this documents the expected structure)
 */
export interface DashboardPageProps {
  // No props - page manages its own state via useExpenses hook
}

// ============================================================================
// Custom Hook Contracts
// ============================================================================

/**
 * Return type of the useExpenses custom hook
 * Encapsulates all expense-related state and operations
 */
export interface UseExpensesReturn {
  /**
   * Array of all expenses, sorted by date (newest first)
   */
  expenses: Expense[];

  /**
   * Computed summary statistics
   */
  summary: ExpenseSummary;

  /**
   * Flag indicating if data is being loaded from localStorage
   */
  isLoading: boolean;

  /**
   * Any error that occurred during storage operations
   */
  error: string | null;

  /**
   * Add a new expense
   * @param expense - Expense data without id/createdAt (auto-generated)
   * @returns The created expense with id and createdAt
   */
  addExpense: (expense: Omit<Expense, 'id' | 'createdAt'>) => Expense;

  /**
   * Delete an existing expense
   * @param id - The unique ID of the expense to delete
   * @returns true if deleted successfully, false if not found
   */
  deleteExpense: (id: string) => boolean;
}

// ============================================================================
// Storage Service Contract
// ============================================================================

/**
 * Interface for the expense storage service
 * Abstracts localStorage operations for testability
 */
export interface ExpenseStorage {
  /**
   * Load all expenses from storage
   * @returns Array of expenses, or empty array if none exist
   * @throws Error if storage is corrupted/unparseable
   */
  loadExpenses(): Expense[];

  /**
   * Save expenses to storage
   * @param expenses - Array of expenses to persist
   * @throws Error if quota exceeded or write fails
   */
  saveExpenses(expenses: Expense[]): void;

  /**
   * Clear all expenses from storage
   */
  clearExpenses(): void;
}

// ============================================================================
// Validation Contracts
// ============================================================================

/**
 * Result of expense validation
 */
export interface ValidationResult {
  /**
   * Whether the data is valid
   */
  isValid: boolean;

  /**
   * Array of validation error messages (empty if valid)
   */
  errors: string[];
}

/**
 * Validation functions interface
 */
export interface ExpenseValidator {
  /**
   * Validate a complete expense object
   */
  validateExpense(expense: Partial<Expense>): ValidationResult;

  /**
   * Validate amount field
   */
  validateAmount(amount: unknown): boolean;

  /**
   * Validate date field
   */
  validateDate(date: unknown): boolean;

  /**
   * Validate category field
   */
  validateCategory(category: unknown): boolean;
}

// ============================================================================
// Calculation Contracts
// ============================================================================

/**
 * Calculation utility functions interface
 */
export interface ExpenseCalculator {
  /**
   * Calculate overall total
   */
  calculateOverallTotal(expenses: Expense[]): number;

  /**
   * Calculate totals by category
   */
  calculateByCategory(expenses: Expense[]): Record<ExpenseCategory, number>;

  /**
   * Calculate current month total
   */
  calculateCurrentMonthTotal(expenses: Expense[]): number;

  /**
   * Calculate last 7 days total
   */
  calculateLast7DaysTotal(expenses: Expense[]): number;

  /**
   * Calculate full summary (convenience method)
   */
  calculateSummary(expenses: Expense[]): ExpenseSummary;
}
